### Run the RSS reader test
GET http://localhost:7166/api/TestRssReader

### Run the Smart Reader test
GET http://localhost:7166/api/TestSmartReader

### Run the Key Vault test
GET http://localhost:7166/api/TestKeyVault

### Test the config
GET http://localhost:7166/api/TestConfig
